#config serve
server:  port: 9092
spring:  application:    name: STOCK-CALC-API
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
